#!/usr/bin/env python3
"""Generate an Arduino-friendly patch header from a patch CSV file.

The input CSV is expected to use rows like:

    quadpatch,name,wall_adjacent=true,x1,y1,x2,y2,x3,y3,x4,y4[,segmentIndex]
    polypatch,name,wall_adjacent=true,x1,y1,x2,y2,x3,y3,...[,segmentIndex]
    circlepatch,name,wall_adjacent=true,center_x,center_y,radius[,segmentIndex]

`wall_adjacent` and `segmentIndex` are optional. If `segmentIndex` is omitted,
the script assigns indices sequentially starting at 0.

The generated header assumes `Patch`, `PATCH_CIRCLE`, `PATCH_QUAD`, and
`PATCH_POLY` are already declared in the sketch before the header is included.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path


HEADER_TEMPLATE = """#pragma once

// Auto-generated by {script_name}.
// Source CSV: {source_name}
// This header expects Patch, PATCH_CIRCLE, PATCH_QUAD, and PATCH_POLY to already exist.

static Patch {array_name}[] = {{
{patch_entries}
}};

static constexpr size_t {count_name} = sizeof({array_name}) / sizeof({array_name}[0]);
"""


@dataclass(frozen=True)
class PatchRecord:
    name: str
    kind: str
    numbers: tuple[float, ...]
    segment_index: int
    wall_adjacent: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a patch CSV into an Arduino header with Patch initializers."
    )
    parser.add_argument("csv_path", type=Path, help="Input CSV path.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output header path. Defaults to an output/ folder beside the CSV.",
    )
    parser.add_argument(
        "--array-name",
        default="patches",
        help="Name of the generated Patch array. Default: patches",
    )
    parser.add_argument(
        "--count-name",
        default="PATCH_COUNT",
        help="Name of the generated patch count constant. Default: PATCH_COUNT",
    )
    return parser.parse_args()


def parse_bool(raw_value: str) -> bool:
    normalized = raw_value.strip().lower()
    if normalized in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if normalized in {"0", "false", "f", "no", "n", "off"}:
        return False
    raise ValueError(f"Invalid boolean value: {raw_value!r}")


def parse_metadata_cells(cells: list[str]) -> tuple[list[str], int | None, bool]:
    number_cells: list[str] = []
    segment_index: int | None = None
    wall_adjacent = False

    for cell in cells:
        lowered = cell.strip().lower()
        if not lowered:
            continue

        if "=" in lowered:
            key, value = lowered.split("=", 1)
            if key == "wall_adjacent":
                wall_adjacent = parse_bool(value)
                continue
            if key in {"segmentindex", "segment_index"}:
                segment_index = parse_int(value)
                continue
            # Ignore unrelated metadata fields written by other tools.
            continue

        number_cells.append(cell)

    return number_cells, segment_index, wall_adjacent


def parse_float(raw_value: str) -> float:
    return float(raw_value.strip())


def parse_int(raw_value: str) -> int:
    return int(raw_value.strip())


def format_number(value: float) -> str:
    return str(int(round(value)))


def escape_cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def format_point(x_value: float, y_value: float) -> str:
    return f"{{{format_number(x_value)}, {format_number(y_value)}}}"


def format_points(points: tuple[tuple[float, float], ...]) -> str:
    if not points:
        return "{}"
    return "{" + ", ".join(format_point(x_value, y_value) for x_value, y_value in points) + "}"


def parse_row(
    row: list[str],
    row_number: int,
    next_segment_index: int,
) -> tuple[PatchRecord | None, int]:
    cells = [cell.strip() for cell in row]
    if not any(cells):
        return None, next_segment_index

    row_type = cells[0].lower()
    if row_type in {"label", "labels", "type"}:
        return None, next_segment_index

    if len(cells) < 2 or not cells[1]:
        raise ValueError(f"Row {row_number}: missing patch name.")

    name = cells[1]
    payload, metadata_segment_index, wall_adjacent = parse_metadata_cells(cells[2:])

    if row_type == "circlepatch":
        if len(payload) == 4:
            segment_index = parse_int(payload[-1])
            payload = payload[:-1]
        elif metadata_segment_index is not None:
            segment_index = metadata_segment_index
        else:
            segment_index = next_segment_index

        if len(payload) != 3:
            raise ValueError(
                f"Row {row_number}: circlepatch rows must contain center x, center y, and radius."
            )
        numbers = tuple(parse_float(value) for value in payload)
    elif row_type == "quadpatch":
        if len(payload) == 9:
            segment_index = parse_int(payload[-1])
            payload = payload[:-1]
        elif metadata_segment_index is not None:
            segment_index = metadata_segment_index
        else:
            segment_index = next_segment_index

        if len(payload) != 8:
            raise ValueError(
                f"Row {row_number}: quadpatch rows must contain 8 coordinate values."
            )
        numbers = tuple(parse_float(value) for value in payload)
    elif row_type == "polypatch":
        if len(payload) < 6:
            raise ValueError(
                f"Row {row_number}: polypatch rows must contain at least 3 x/y point pairs."
            )

        if len(payload) % 2 == 1:
            segment_index = parse_int(payload[-1])
            payload = payload[:-1]
        elif metadata_segment_index is not None:
            segment_index = metadata_segment_index
        else:
            segment_index = next_segment_index

        if not payload:
            raise ValueError(f"Row {row_number}: polypatch row is missing coordinate values.")

        if len(payload) < 6 or len(payload) % 2 != 0:
            raise ValueError(
                f"Row {row_number}: polypatch rows must contain 3 or more complete x/y pairs."
            )

        if any(not value for value in payload):
            raise ValueError(f"Row {row_number}: polypatch coordinates cannot be blank.")

        numbers = tuple(parse_float(value) for value in payload)
    else:
        raise ValueError(f"Row {row_number}: unsupported patch type {cells[0]!r}.")

    next_segment_index = max(next_segment_index, segment_index + 1)
    return PatchRecord(name, row_type, numbers, segment_index, wall_adjacent), next_segment_index


def load_patches(csv_path: Path) -> list[PatchRecord]:
    patches: list[PatchRecord] = []
    next_segment_index = 0

    with csv_path.open(newline="", encoding="utf-8-sig") as csv_file:
        reader = csv.reader(csv_file)
        for row_number, row in enumerate(reader, start=1):
            patch, next_segment_index = parse_row(
                row,
                row_number,
                next_segment_index,
            )
            if patch is not None:
                patches.append(patch)

    if not patches:
        raise ValueError(f"No patch rows found in {csv_path}.")

    return patches


def resolve_default_output_path(csv_path: Path) -> Path:
    output_dir = csv_path.parent
    if output_dir.name.casefold() != "output":
        output_dir = output_dir / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir / f"{csv_path.stem}.h"


def format_patch_entry(patch: PatchRecord) -> str:
    if patch.kind == "circlepatch":
        center_x, center_y, radius = patch.numbers
        center = format_point(center_x, center_y)
        radius_text = format_number(radius)
        points = ()
        shape_name = "PATCH_CIRCLE"
    else:
        point_values = tuple(
            (patch.numbers[index], patch.numbers[index + 1])
            for index in range(0, len(patch.numbers), 2)
        )
        center = format_point(0.0, 0.0)
        radius_text = "0"
        points = point_values
        shape_name = "PATCH_POLY" if patch.kind == "polypatch" else "PATCH_QUAD"

    geometry = (
        f"    {center},\n"
        f"    {radius_text},\n"
        f"    {format_points(points)},\n"
        f"    {len(points)}"
    )

    return (
        "  {\n"
        f'    "{escape_cpp_string(patch.name)}",\n'
        f"    {shape_name},\n"
        f"    {patch.segment_index},\n"
        f"    {'true' if patch.wall_adjacent else 'false'},\n"
        f"{geometry}\n"
        "  }"
    )


def build_header(
    patches: list[PatchRecord],
    source_name: str,
    script_name: str,
    array_name: str,
    count_name: str,
) -> str:
    patch_entries = ",\n".join(format_patch_entry(patch) for patch in patches)
    return HEADER_TEMPLATE.format(
        script_name=script_name,
        source_name=source_name,
        array_name=array_name,
        patch_entries=patch_entries,
        count_name=count_name,
    )


def main() -> int:
    args = parse_args()
    csv_path = args.csv_path.resolve()
    output_path = args.output.resolve() if args.output else resolve_default_output_path(csv_path)

    patches = load_patches(csv_path)
    header_text = build_header(
        patches=patches,
        source_name=csv_path.name,
        script_name=Path(__file__).name,
        array_name=args.array_name,
        count_name=args.count_name,
    )

    output_path.write_text(header_text, encoding="utf-8", newline="\n")
    print(f"Wrote {len(patches)} patches to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
